name: Build
on:
  push:
    branches:
      - '*'

jobs:
  build:
    name: 👷 Build
    runs-on: ubuntu-latest
    steps:
    - name: 🛑 Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.10.1
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: ⬇️ Check out
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 1
    - run: echo "Building"
  deploy-staging:
    name: 🚀 Deploy / Staging
    runs-on: ubuntu-latest
    needs:
    - "build"
    if: github.ref == 'refs/heads/main'
    steps:
    - name: ⬇️ Check out
      uses: actions/checkout@v3.1.0
      with:
        fetch-depth: 1
    - name: 🐋 Set up Docker Buildx
      uses: docker/setup-buildx-action@v2
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.PAT }} # `PAT` is a secret that contains your Personal Access Token with `write:packages` scope
    - name: 🐋 Build and push docker image
      uses: docker/build-push-action@v3.1.1
      with:
        context: .
        file: Dockerfile
        platforms: linux/amd64
        push: true
        tags: |
          ghcr.io/gimlet-io/gais:${{ github.sha }}
