name: Branch Deleted
on: #delete
  push:
    branches:
      - '*'
jobs:
  delete:
    # if: github.event.ref_type == 'branch'
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/gimlet-io/gimlet-cli:v0.18.0-rc.11
    steps:
      - name: Clean up
        run: |
          echo "Clean up for branch ${{ github.event.ref }}"
          APP_NAME=$(gimlet manifest template -f .gimlet/preview-gais.yaml | yq 'select(document_index == 1).metadata.name')
          echo $APP_NAME
